### ISSUE TITLE
Problem with Metamask

### ISSUE THREAD

**Issue by seemo92** [acclrate/cronos-dapp-basic-3#1]
index.ts:225 Uncaught (in promise) Error: call revert exception (method="balanceOf(address)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at Logger.makeError (index.ts:225:1)
    at Logger.throwError (index.ts:237:1)
    at Interface.decodeFunctionResult (interface.ts:425:1)
    at Contract.<anonymous> (index.ts:392:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:2:1)

Hi, I Clone your project.
This is the message I have when i connect my Metamask, do you have any idea ?

Thanks for your help

**Comment by kentimsit** [comment]
@seemo92 looks like perhaps you are not connected to Cronos testnet in your wallet? otherwise can you recap the steps that you took?
